# Generated by Django 4.2 on 2023-04-28 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choices_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='vptess',
            new_name='votes',
        ),
    ]
